### PR TITLE
Add concurrent processor

### PR DESCRIPTION
**Pull request by emintham**
- Refactors argument passing for ProcessDump.
- Make data structures in processors concurrency safe.
- Add concurrent processor + tests.
- Update README and example config.

### CODE REVIEW

**Comment by emintham** [comment]
I've tried fixing the errors and I'm stuck at the settings of coveralls
```
Bad response status from coveralls: 422
{"message":"Couldn't find a repository matching this job.","error":true}
```
I've tried to set up coveralls for my fork but that doesn't feel like the right solution..

**Comment by junkert** [comment]
Awesome! Thank you @emintham . I'm currently out of town but will be back next week (2020/08/24). I will start reading through this and add comments and get back to you then.

Again thank you for all the work!

**Comment by emintham** [comment]
Sounds good @junkert !

**Review by junkert — APPROVED** [review]
Thanks @emintham for this PR! Going to merge this in and then set version 2.0 on the tag. I'll try to find some time to update the documentation unless you want to help with that as well 😊

**Comment by emintham** [comment]
Hey thanks @junkert! I believe I added some stuff in README and examples in the MR. I'm kinda busy over the next little bit so I might not have time to add other docs.

**Pull request merged**
